import { Country } from './country';
import { AssetFile } from './asset-file';
import { Game } from './game';
import { GameGenre } from './game-genre';
import { PointItem } from './point-item';
import { MarketItem } from './market-item';

export interface User {
  id: number;
  accountName: string;
  avatarBorder: PointItem | null;
  cart: Game[];
  cartCount: number;
  country: Country;
  customUrl: string;
  displayName: string;
  email: string;
  level: number;
  status: string;
  friendCode: string;
  friends: User[];
  games: Game[];
  gamesByOwnedMarketItems: Game[];
  ingoingFriendRequests: User[];
  marketItemsByGame: { data: MarketItem[]; totalPages: number };
  miniProfileBackground: PointItem | null;
  outgoingFriendRequests: User[];
  ownedAvatarBorders: PointItem[];
  ownedMiniProfileBackgrounds: PointItem[];
  ownedProfileBackgrounds: PointItem[];
  profileBackground: PointItem | null;
  mostViewedGenres: GameGenre[];
  points: number;
  profilePicture: AssetFile;
  profileTheme: string;
  realName: string;
  receivedGiftsCount: number;
  receivedInvitesCount: number;
  receivedMessagesCount: number;
  receivedProfileCommentsCount: number;
  reportCounts: number;
  stream: string;
  summary: string;
  suspendedAt: Date;
  walletBalance: number;
  wishlist: Game[];
  wishlistCount: number;
}
